import { Inter } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import Switch from "@/components/Switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Linkly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <Box className="flex flex-col min-h-screen">
          <Box className="!fixed !top-1/2 !right-[-1.53vw] !z-10 !rotate-90 !hidden xl:!inline">
            <Switch />
          </Box>
          {children}
        </Box>
      </body>
    </html>
  );
}
